[package]
name = "sql-id-slicer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.32", features = ["derive"] }
console = "0.16.2"
dialoguer = { version = "0.12.0", features = ["editor"] }
sqlparser = "0.61.0"
