[package]
name = "sql-id-slicer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.32", features = ["derive"] }
console = "0.15.10"
dialoguer = { version = "0.11.0", features = ["editor"] }
inquire = "0.9.3"
regex = "1.12.2"
